version: '3'
services:

  proxy:
    container_name: nginx-certbot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./letsencrypt:/etc/letsencrypt 
      - ./default.conf:/etc/nginx/conf.d/default.conf
